development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: balloons_dev
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: balloons_test
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: balloons
  pool: 5
  username: root
  password: ctrhtnfhbfn
  socket: /var/run/mysqld/mysqld.sock
  queue:
    adapter: mysql2
    encoding: utf8
    database: balloons
    username: root
    password: ctrhtnfhbfn
    socket: /var/run/mysqld/mysqld.sock
